_target_: src.models.brats_module.BratsLitModule

optimizer:
  _target_: torch.optim.AdamW
  _partial_: true
  lr: 0.001
  weight_decay: 0.001 # L2 Penalty to prevent overfitting by penalizing large weights in the model

scheduler:
  _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
  _partial_: true
  factor: 0.1 # Specifies the factor by which the learning rate will be reduced.
  patience: 5 # If the monitored metric (i.e. val_score) is not increased in the 5 consecutive epochs, the learning_rate will be reduced by the specified factor

net:
  _target_: src.models.components.unet.UNet
  spatial_dims: 3 # 3 for using 3D ConvNet and 3D Maxpooling
  in_channels: 4 # since 4 modalities
  out_channels: 4 # 4 sub-regions to segment
  channels: [16, 32, 64, 128, 256]
  # channels: [64, 128, 256, 512, 1024]
  strides: [2, 2, 2, 2]
  norm: BATCH
  dropout: 0.4
  

# compile model for faster training with pytorch 2.0
# compile: false


# # Initialize the U-Net model
# model = UNet(
#     spatial_dims=3, # 3 for using 3D ConvNet and 3D Maxpooling
#     in_channels=4, # since 4 modalities
#     out_channels=4, # 4 sub-regions to segment
#     channels=(16, 32, 64, 128, 256),
#     strides=(2, 2, 2, 2)
# )